sidekiq-cron/sidekiq-cron

.travis.yml

Because Sidekiq does not already support MRI 1.9
https://github.com/mperham/sidekiq/blob/v3.3.4/lib/sidekiq.rb#L3

Don't test on ruby 1.9.3

---

test/unit/job_test.rb

When run test from 0:00 to 2:00 every day, always fail a test.
When run test at 2015/5/18 0:30, raised this error.
```
FAIL (0:00:00.165) test_: Cron Job cron test should return previous day.
<"2015-05-17-02-01-00"> expected but was
<"2015-05-18-02-01-00">.
```
I think expected date is wrong

Fix a test that depends on current time

---

lib/sidekiq/cron/job.rb
test/unit/job_test.rb

When remove or rename jobs from arg of `Sidekiq::Cron::Job#load_from_hash` (or `Sidekiq::Cron::Job#load_from_array`) after stored to redis, old jobs are continue remaining permanently!
```ruby
hash = {
'job1' => { ... },
'job2' => { ... },
}
Sidekiq::Cron::Job.load_from_hash hash
Sidekiq::Cron::Job.all.map(&:name)
hash = {
'job2' => { ... },
}
Sidekiq::Cron::Job.load_from_hash hash
Sidekiq::Cron::Job.all.map(&:name)
```
`job1` is removed from hash, but  continue remaining permanently in redis !
```ruby
hash = {
'old_job1' => { ... },
'job2' => { ... },
}
Sidekiq::Cron::Job.load_from_hash hash
Sidekiq::Cron::Job.all.map(&:name)
hash = {
'new_job1' => { ... },
'job2' => { ... },
}
Sidekiq::Cron::Job.load_from_hash hash
Sidekiq::Cron::Job.all.map(&:name)
```
Both `old_job1` and `new_job1` is …

Add cleanup removed job methods

---

README.md
lib/sidekiq/cron.rb
lib/sidekiq/cron/web.rb
test/test_helper.rb

This allows to use sidekiq-cron without the web-ui-integration.
Now you need to explicitly load the cron extension in your routes:
```ruby
require 'sidekiq/web'
require 'sidekiq/cron/web'
mount Sidekiq::Web => '/sidekiq'
```

Disable auto-loading of Sidekiq web-ui-extension

---

lib/sidekiq/cron/job.rb

Sidekiq::Cron::Job.load_from_hash support "queue" parameter without "default".

initialize "queue" parameter

---

Gemfile
sidekiq-cron.gemspec
test/test_helper.rb

We had a bundler conflict for tilt, `> 2.0.0` vs `2.0.1` so we checked and noticed that Tilt is no longer being used by this gem and can be removed safely.

Remove tilt dependency

---

lib/sidekiq/cron/job.rb

Ensure that `Sidekiq::Cron::Job#formated_last_time` returns the time in
an expected time format. Otherwise, configurations that override the
Ruby/Rails default time format can lead to jobs never being added to the
queue.

Ensure time format

---

lib/sidekiq/cron/poller.rb

Poll interval has been deprecated and the option removed
https://github.com/mperham/sidekiq/commit/4255aaf0
and
https://github.com/mperham/sidekiq/commit/b5ab9c9f

Use new poll_interval_average option

---

lib/sidekiq/cron/job.rb
test/unit/job_test.rb

Added a description key to job definition which could be very useful in some cases. For instance, [resque-scheduler](https://github.com/resque/resque-scheduler) already has such key

Add description to Job

---

README.md

Thank you very much for putting this out, I just migrated from sidetiq and find this gem to be very superior in many ways.
But I just run into a problem, where the current documentation stated that the cronline is always based on UTC. I found that not to be the case. Since you are using rufus-scheduler you are using the systems time as base.
Also rufus-scheduler supports timezones in a cronline since version 2.0.7. The minimum version of rufus-scheduler this gem depends on is currently >= 2.0.24, so I think that should work.

Add cronline timezone info to README

---

Gemfile
lib/sidekiq/cron.rb
lib/sidekiq/cron/job.rb
lib/sidekiq/cron/launcher.rb
lib/sidekiq/cron/poller.rb
sidekiq-cron.gemspec
test/test_helper.rb
test/unit/poller_test.rb

I've refactored the poller to work with the recent Sidekiq 4 changes. It is now inheriting from the Sidekiq poller which makes it more straightforward. Its possible that sidekiq changes could break it in the future, but I thought this would be better than duplicating the logic, especially since the gem is already pretty heavily dependent on the Sidekiq classes.
This drops support for prior versions of Sidekiq. I didn't have any ideas for a clean way to support them with the difference in dependencies. This update could be released as a major version and only support Sidekiq 4 going forward. Otherwise let me know how you'd like to support them both.

Sidekiq 4 support

---

README.md

This fixes the problem I mentioned in #71

Avoid displaying jobs when starting console

---

lib/sidekiq/cron/job.rb
test/unit/job_test.rb

We are running sidekiq-cron in an environment where it should enqueue jobs whose class definition exists outside of its own codebase. Sidekiq workers running on a remote host will read this queue and perform the jobs.
The ActiveJob check tries to constantize the class name, then raises an exception if the class doesn't exist. (If you agree) I think the job definition should still be enqueued, and class lookups should be resolved by the workers instead of by sidekiq-cron

job.enque! should not raise exception when class is unknown

---

README.md
lib/sidekiq/cron/job.rb

As a user I want to use `sidekiq-cron` in my rails project with custom `ActiveJob.queue_name_delimiter`
The default queue name prefix delimiter is '_'. This can be changed by setting `queue_name_delimiter` 
in Job properties:
```ruby
{
'name'  => 'name_of_job', #must be uniq!
'cron'  => '1 * * * *',
'class' => 'MyClass',
#OPTIONAL
'queue' => 'name of queue',
'args'  => '[Array or Hash] of arguments which will be passed to perform method',
'active_job' => true,  # enqueue job through rails 4.2+ active job interface
'queue_name_prefix' => 'prefix' # rails 4.2+ active job queue with prefix
'queue_name_delimiter' => '.'  # rails 4.2+ active job queue with custom delimiter
}
```

Permit to use ActiveJob::Base.queue_name_delimiter

---

lib/sidekiq/cron/locales/en.yml

Randomly noticed the above. Button should read "Enable", since it re-enables a job.

[FIX] Fix a tpyo on the cron dashboard for enabling a job

---

lib/sidekiq/cron/job.rb
test/unit/job_test.rb

I noticed that if a cron job is resaved within ~30 seconds of when it supposed to be enqueued next it won't be enqueued. The resave in my case is a result of the application being restarted and the initializers being triggered. The failure to enqueue appears to be caused by line 417 in job#save. 
I am curious about the need to set the job_enqueued_key on save, but my assumption is so that new jobs aren't immediately queued. Let me know if my assumption is incorrect.
Thanks.

Only update the enqueued key on save if there isn't already one

---

Gemfile
lib/sidekiq/cron/job.rb
lib/sidekiq/cron/web_extension.rb
test/test_helper.rb
test/unit/job_test.rb

1. Fix sidekiq web extension bugs when upgrade to Sidekiq 4.2.1
Sidekiq 4.2.1 remove sinatra, web extension doesn't work.
2. Use `perform_later` / `perform_async` for ActiveJob/Sidekiq Woker when job constant exists

Upgrade to sidekiq 4.2.1

---

Gemfile
lib/sidekiq/cron/job.rb

ERROR: CRON JOB: can't convert Rufus::Scheduler::ZoTime into an exact number.

Fix rufus-scheduler 3.3.0 ZoTime operation bug.

---

lib/sidekiq/cron/poller.rb

When having lot of jobs to schedule, time can go and 60s window is too small to enqueue them all.
Remember time of poller enqueue and then use it for all jobs

Fix poller to not adding all jobs and given period of time

---

README.md

Hi,
Thanks for this gem. I spent a little bit of time today worrying about the possibility of sidekiq-cron running duplicate jobs in heroku when I scale up the number of sidekiq worker dynos. Came across https://github.com/ondrejbartas/sidekiq-cron/issues/137 which made it clear I didn't need to worry about that.
Thought it would be nice to mention this in the README. I pretty much just recycled @ondrejbartas explanation from the referenced issue. Hopefully it's accurate.

README is explicit that it's safe to use sidekiq-cron with multiple processes

---

lib/sidekiq/cron/job.rb

This replaces `Time.parse` with `Time.strptime`. `strptime` is more explicit and more consistent across Ruby versions. This change should resolve #183.

Prefer ::strptime as it is more explicit and consistent

---

.travis.yml

Ruby 2.2.8/2.3.5/2.4.2 has been released
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-2-8-released/
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-3-5-released/
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-4-2-released/

CI against Ruby 2.2.8/2.3.5/2.4.2

---

README.md

I noticed that the README is outdated :)
The default poll interval is now 30s not 10s.

Fix poll interval description in README

---

README.md

As of rufus-scheduler v3.3.3 (https://github.com/jmettraux/rufus-scheduler/commit/dc9e9df051b2d9f5379f3cd5c703f078b35b8e3a), the Rails timezone is used by default when Rails is present.

Clarify rufus-scheduler uses Rails timezone in Readme

---

lib/sidekiq/cron/job.rb
test/unit/job_test.rb

Fixes issue where sidekiq-cron doesn't add the "wrapped" argument that is used by ActiveJob and Sidekiq to determine the original class
Rails has a test for it: https://github.com/rails/rails/blob/9d9f752661c31b3063d55bec14e797c957d2bb7d/activejob/test/integration/queuing_test.rb#L30 
And Sidekiq uses it in their API: https://github.com/mperham/sidekiq/blob/2ed92600fa71a9c275189d01df369ad4f8b9ca32/lib/sidekiq/api.rb#L322
Without the 'wrapped' param it takes the entire "args" class as the job name, causing all kinds of issues.

Add 'wrapped' argument to ActiveJob message

---

Gemfile
lib/sidekiq/cron/job.rb
sidekiq-cron.gemspec
test/integration/performance_test.rb
test/unit/job_test.rb
test/unit/poller_test.rb

Addresses https://github.com/ondrejbartas/sidekiq-cron/issues/199
Sidekiq-cron is not using rufus-scheduler itself but rather its cron logic which recently got spun off in the fugit gem (https://github.com/floraison/fugit).
This patch makes Sidekiq-cron depend directly on fugit instead of rufus-scheduler.
A refinement would be to cache the parsed cron line in the Sidekiq-cron Job instance so that there is no need to reparse each time.
Here is the `rake test` output after patching. Please note that I did not address the remaining five errors, they seem unrelated, out of the scope for this patch :  [test1.txt](https://github.com/ondrejbartas/sidekiq-cron/files/2015048/test1.txt)

Use directly fugit instead of rufus-scheduler

---

lib/sidekiq/cron/job.rb
test/unit/job_test.rb

This is alternate implementation of https://github.com/ondrejbartas/sidekiq-cron/pull/209, although I do believe https://github.com/ondrejbartas/sidekiq-cron/pull/209 to be the more correct implementation. Only difference is that this one doesn't require a breaking change.
As far as I can tell `Time.strptime` will use the system time, `DateTime.strptime` will assume the date string is UTC.
Example:
```ruby
irb(main):004:0> LAST_ENQUEUE_TIME_FORMAT = '%Y-%m-%d %H:%M:%S'
=> "%Y-%m-%d %H:%M:%S"
irb(main):005:0> Time.now
=> 2018-07-16 16:30:47 -0400
irb(main):029:0> ref_time = Time.now.utc
=> 2018-07-16 20:33:44 UTC
irb(main):030:0> time_string = ref_time.strftime(LAST_ENQUEUE_TIME_FORMAT)
=> "2018-07-16 20:33:44"
irb(main):031:0> Time.strptime(time_string, LAST_ENQUEUE_TIME_FORMAT)
=> …
```

Switch Time.strptime to DateTime.strptime to always parse as UTC

---

lib/sidekiq/cron/job.rb
lib/sidekiq/cron/locales/en.yml
lib/sidekiq/cron/views/cron.erb
lib/sidekiq/cron/views/cron.slim
lib/sidekiq/cron/views/cron_show.erb
lib/sidekiq/cron/views/cron_show.slim
lib/sidekiq/cron/web_extension.rb
test/test_helper.rb
test/unit/job_test.rb
test/unit/web_extension_test.rb

I have added the enqueue time/jid history for the cron jobs. This feature is also present in _Sidekiq Ent_.
This will be quite a useful feature.
The default history size will be 10. User can also change it by adding `:cron_history_size` in their `sidekiq.yml` file.
**Have a look:**

Added jid history, just like Sidekiq Enterprise

---

Dockerfile
docker-compose.yml
lib/sidekiq/cron/web_extension.rb
test/integration/performance_test.rb
test/test_helper.rb
test/unit/poller_test.rb
test/unit/web_extension_test.rb

* Upgrades Ruby to 2.4
* Updates the docker-compose.yml file so that it uses `bundle exec` and adds a volume to load the source code
* Solves Mocha deprecation warning
* Solves redis-namespace deprecation warning
* Fixes tests by increasing the performance tests waiting time to 40 seconds and removing the use of `present?`
Closes #271 and #272.

Updates Docker files and fixes tests (Closes #271 #272)

---

lib/sidekiq/cron/locales/en.yml
lib/sidekiq/cron/views/cron.erb
lib/sidekiq/cron/views/cron.slim
lib/sidekiq/cron/views/cron_show.erb
lib/sidekiq/cron/views/cron_show.slim
lib/sidekiq/cron/web_extension.rb

I accidentally clicked on an `enqueue` button and kicked off a worker that was not supposed to be run. This adds javascript confirmation dialogs to those buttons so this accident is less likely to happen.

Add javascript confirmation to enqueue buttons

---

README.md

Default is 30, so isn't 30 more accurate here?

Fix description about interval value.

---

lib/sidekiq/cron.rb
lib/sidekiq/cron/job.rb

In the case of two or more Sidekiq workers the job hash in Redis can be
left in a partly deleted state after one worker deletes the job and
another worker sets the last_enqueue_time value. If this happens
before this commit then calls to Job.find will return an invalid job
that doesn't have a  name (or any properties but last_enqueue_time)
and can't be destroyed. After this commit nil is returned if the Job is
not valid.

validate jobs in Job.find

---

lib/sidekiq/cron/job.rb

Fixes #274
I am not sure if this is the way the maintainer wants to move on with the gem, but one approach would be adding a new argument for retro compatibility purposes and convert the argument if the argument is ready.
Essentially, I created this argument called `symbolize_args` and in case it was set, we'd symbolize the hash keys so before we actually send them to ActiveJob.
Can I get some comments here if this is the way to move forward? I'll implement tests once confirmed.

[RFC] Add ability to symbolize keys so it can be used with keyword args

---

lib/sidekiq/cron.rb

There is a deprecation warning still in place after https://github.com/ondrejbartas/sidekiq-cron/pull/288 was merged.
This PR is intended to remove the warning as there is no more sense to set `exists_returns_integer` as PR above introduced proper method invocation based on redis version.

redis: invocation of deprecated functionality removed

---

lib/sidekiq/cron/job.rb

`Cron Jobs - add job with name:` seemed like a warning that some action needs to be taken ¯\\_(ツ)\_/¯

Make log message more obvious

---

README.md

Updates the README to mention this undocumented (and regularly requested!) feature.

Update README to mention second-precision jobs

---

Rakefile

By requiring these Bundler provided tasks, we have now access to cool 😎  tools to work more easily (release, build locally, ...) with the gem:
```
$ rake -T
rake build             # Build sidekiq-cron-1.3.0.gem into the pkg directory
rake build:checksum    # Generate SHA512 checksum if sidekiq-cron-1.3.0.gem into the checksums directory
rake clean             # Remove any temporary products
rake clobber           # Remove any generated files
rake install           # Build and install sidekiq-cron-1.3.0.gem into system gems
rake install:local     # Build and install sidekiq-cron-1.3.0.gem into system gems without network access
rake release[remote]   # Create tag v1.3.0 and build and push sidekiq-cron-1.3.0.gem to rubygems.org
rake test              # Run tests
rake test:integration  # Run …
```

release gem using Bundler

---

Dockerfile
lib/sidekiq/cron/job.rb
lib/sidekiq/cron/poller.rb
sidekiq-cron.gemspec

This PR is focused to adapt the project to support the changes coming from the Sidekiq 6.5.
- The sidekiq/util file is not available anymore. And we don't really need it. I just changed to use the logger from the Sidekiq module;
- Update the Ruby version references to 2.6 (dockerfile) and some dev dependencies;
- The Poller class requires an argument when Sidekiq version is >= 6.5. I fixed it passing the Sidekiq options. Seems like the right workaround as I could see in the sidekiq repo.
Closes #330

Fix/sidekiq 6.5 breaking changes

---

README.md
lib/sidekiq/cron.rb
lib/sidekiq/cron/schedule_loader.rb
test/unit/job_test.rb

fixes #250
With this change, we do not need to explicitly keep an initializer to load the `config/schedule.yml` file. If someone wants to use a different name, that's possible by putting the following configuration in sidekiq options.
```yml
default: &default
:concurrency: 5
production:
<<: *default
cron_schedule_file: "config/schedule_prod.yml"
queues:
- default
```
For some reason, if someone decides to go the initializer way, that'll work too. Have verified that the jobs don't enqueue again.
As an added benefit, this gives flexibility in having different schedules for different environments. 
_(Not sure why that will be needed but, it's there😃)_
----

Adds support for auto-loading the `config/schedule.yml` file

---

README.md
lib/sidekiq/cron/job.rb

Since Sidekiq 6.5.0, using `Sidekiq.options[:config_var]` throws a warning: https://github.com/mperham/sidekiq/pull/5340/files#diff-2eecd3565b38823c09513903afa6686627d3ba8d883d520d3a83db61375e5ddeR72
> 2022-06-11T09:47:02.416Z pid=88697 tid=2k9 WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: [".../gems/sidekiq-cron-1.5.1/lib/sidekiq/cron/job.rb:481:in `add_jid_history'", ".../gems/sidekiq-cron-1.5.1/lib/sidekiq/cron/job.rb:73:in `enque!'"]
This change uses the new API, if it's available.
Before (mperham/sidekiq@eddc11ba): `Sidekiq.respond_to?(:[]) # => false`
After (mperham/sidekiq@67daa7a4): `Sidekiq.respond_to?(:[]) # => true`

Fix Sidekiq.options deprecation warning

---

CHANGELOG.md
README.md
lib/sidekiq/cron/job.rb
test/unit/job_test.rb

I'm not sure why fugit was locked on 1.1.
Upgrading the dependency allows to use recent features such as natural language definitions (ie `"every 30 minutes"`).
This will fix #229
Related to #293

Allow natural language definitions

---

lib/sidekiq/cron/job.rb
lib/sidekiq/cron/poller.rb
lib/sidekiq/cron/schedule_loader.rb
lib/sidekiq/cron/sidekiq_options.rb
lib/sidekiq/options.rb

`Sidekiq.options` warning should be resolved on PR #338. 
But on PR #337 still used `Sidekiq.options` at https://github.com/ondrejbartas/sidekiq-cron/pull/337/files#diff-74c7adba1e1cde8fd26e2a46f0e03b37e9039f3a73ff16776ca21f4555ff7185R6

Fix Sidekiq.options warning for sidekiq-cron v1.6.0

---

CHANGELOG.md
README.md
lib/sidekiq/cron/job.rb
lib/sidekiq/cron/version.rb

Main changes:
- Enable to use cron notation in natural language (ie `every 30 minutes`): #312
- Fix `date_as_argument` feature to add timestamp argument at every cron job execution: #329
- Make auto schedule loading compatible with Array format: #345
**Full diff** 👉🏼 https://github.com/ondrejbartas/sidekiq-cron/compare/v1.6.0...master
@ondrejbartas @honzasterba I think these changes deserve a new release ✨ ✨

Prepare release v1.7.0

---

lib/sidekiq/cron/views/cron.erb

Update job name color on dark theme to resolved issue #347

Update style for disabled job in dark theme.

---

CHANGELOG.md
lib/sidekiq/cron/job.rb
test/unit/job_test.rb

redis-rb v4.8.0 gives a deprecation warning when calling `sadd` and
`srem` with a single argument:
https://github.com/redis/redis-rb/blob/4.x/CHANGELOG.md#480
```
Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.
```
Resolving the deprecation warning by following Sidekiq's approach of
wrapping the argument as an array:
https://github.com/mperham/sidekiq/commit/09dacfed8f3f0b42833122b138639d22c71e3d56
Fixes #355

Fix deprecation warnings with redis-rb v4.8.0

---

lib/sidekiq/cron/launcher.rb
lib/sidekiq/cron/poller.rb

Avoid setting global config so that we do not change the behavior of the Sidekiq scheduled set poller.
Closes #358

Fix poller affecting Sidekiq scheduled set poller

---

README.md
lib/sidekiq/cron/poller.rb

Uses a different Sidekiq option because `average_scheduled_poll_interval` has a default value of 5 seconds.
I know this is a breaking change but so was the bug that changed it to 5 seconds from 30 seconds.
Closes https://github.com/ondrejbartas/sidekiq-cron/issues/361

Fix default polling interval

---

lib/sidekiq/cron/poller.rb

We don't use the process count parameter so we just set a default value so that this works with previous versions too
Closes #365

Fix compatibility with Sidekiq v6.5.7

---

README.md
lib/sidekiq/cron/launcher.rb
lib/sidekiq/cron/poller.rb
test/unit/launcher_test.rb

When running with very many Sidekiq processes, polling on each one of them can be expensive and unnecessary too.
This allows disabling polling by setting `cron_poll_interval` to zero.

Allow disabling of cron polling

---

CHANGELOG.md
README.md
sidekiq-cron.gemspec
test/test_helper.rb

- some random simplications and typos in `test_helper.rb`
- remove development dep `redis-namespace`
- update links to new home (GH already supports automatic redirects for repo renames, but let's use the new link everywhere is possible)

simplify test_helper.rb + remove dev dep redis-namespace + update links to new home

---

README.md

We are not really active in that place, so better to move to (async) GH discussions?
> Discussions is the space for your community to have conversations, ask questions and post answers without opening issues.

[docs] remove link to gitter chat

---

.github/workflows/ci.yml
Gemfile
README.md
sidekiq-cron.gemspec

Closes #380
Also, remove Ruby 2.6 support. This version is pretty EOL, so time to stick to 2.7 as the minimal.

[CI] Allow to test different Sidekiq versions

---

lib/sidekiq/cron/launcher.rb

Formerly, `Sidekiq::Launcher.new` took one "config" argument. As of v7 there's a possibility of  "embedded" being passed in. ex: `Sidekiq::Launcher.new(config, embedded: true)`
Presently, when running sidekiq-cron with embedded mode, we get an exception. To reproduce this, load sidekiq-cron with Sidekiq in "[embedded mode](https://www.mikeperham.com/2022/10/27/sidekiq-7.0-embedding/)"
This PR adds optional keyword args to pass along, to support `embedded` and to allow for future keyword args that might get added.

Allow for keyword args in Poller

---

lib/sidekiq/cron/job.rb
test/unit/job_test.rb

Fixed an error related to `date_as_argument` option that occurred when temporarily deploying multiple versions of sidekiq-cron.
This problem affects when you have a deployment where multiple versions of sidekiq-cron temporarily exist (such as [rolling update](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-type-ecs.html))
In this case, an option created in a newer version was unintentionally processed in the older version (1.6.0) and did not work correctly.
For more information, I have attempted to explain this at https://github.com/sidekiq-cron/sidekiq-cron/issues/350#issuecomment-1409798837
This PR avoids this problem by changing the hash of options created in the new version to work in the 1.6.0 version as well.
close: …

fix argument error problem update from 1.6.0 to newer

---

lib/sidekiq/cron/job.rb

On my laptop in Japanese-language environment, loading `@last_enqueue_time` raises a parse error:
```
2022-08-08T05:59:06.992Z pid=58672 tid=2kqk WARN: Date::Error: invalid date
2022-08-08T05:59:06.992Z pid=58672 tid=2kqk WARN: /Users/ryotarai/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sidekiq-cron-1.7.0/lib/sidekiq/cron/job.rb:632:in `parse'
/Users/ryotarai/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sidekiq-cron-1.7.0/lib/sidekiq/cron/job.rb:632:in `rescue in parse_enqueue_time'
/Users/ryotarai/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sidekiq-cron-1.7.0/lib/sidekiq/cron/job.rb:629:in `parse_enqueue_time'
/Users/ryotarai/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sidekiq-cron-1.7.0/lib/sidekiq/cron/job.rb:285:in `initialize'
```
This PR makes `@last_enqueue_time` be …

Make last_enqueue_time be always an instance of Time.

---

sidekiq-cron.gemspec

See: https://github.com/advisories/GHSA-23c2-gwp5-pxw9
@nyuta01 I just received a 🤖 dependabot warning due to that version.

[deps] upgrade required globalid version to fix a potential security vulnerability

---

lib/sidekiq/cron/schedule_loader.rb
test/unit/job_test.rb
test/unit/schedule_loader_test.rb

Clear old jobs while loading the jobs from schedule

---

lib/sidekiq/cron/job.rb

Hi.
Sidekiq now prints a warning about the usage of `hmset` when using sidekiq-cron. This Redis command [was deprecated in Redis v4](https://redis.io/commands/hmset/).
sidekiq-cron requires Sidekiq >= 6 which itself requires Redis >= 4. So I would argue that we can safely use `hset` (and go up a minor version).
I also don't see the need to convert the hash to an array. Unless there was a specific reason for that?

Use hset instead of deprecated hmset

---

README.md

I believe describing the default value of `queue_name_delimitrer` should reduce confusion when users read the document.
https://github.com/sidekiq-cron/sidekiq-cron/blob/7cc3d13150e7fecce6b2f71d3c86a640e9ae6436/lib/sidekiq/cron/job.rb#L119

Avoid confusion about `queue_name_delimitrer` default value on README

---

sidekiq-cron.gemspec

```console
$ gem build -o before
$ git switch reduce-gem-size
$ git build -o after
$ du -sh before after
32K	before
24K	after
```
=> **-8K** saved

Reduce gem size by excluding test files

---

lib/sidekiq/cron/schedule_loader.rb

Starting with 7.0, Sidekiq can be run in embedded mode where `Sidekiq.server?` returns `false`
Reference: https://www.mikeperham.com/2022/10/27/sidekiq-7.0-embedding/

remove Sidekiq.server? check from schedule loader

---

lib/sidekiq/options.rb
test/unit/launcher_test.rb

`SIDEKIQ_VERSION=6 bundle exec rake test` was previously failing since `Sidekiq` doesn't have options:
```
1) Error:
Cron launcher::initialization#test_0001_initializes poller with default poll interval when not configured:
NoMethodError: undefined method `[]' for Sidekiq:Module
config[:cron_poll_interval] = DEFAULT_POLL_INTERVAL if config[:cron_poll_interval].nil?
^^^^^^^^^^^^^^^^^^^^^
/Users/stanhu/github/sidekiq-cron/lib/sidekiq/cron/launcher.rb:20:in `initialize'
/Users/stanhu/github/sidekiq-cron/test/unit/launcher_test.rb:14:in `new'
/Users/stanhu/github/sidekiq-cron/test/unit/launcher_test.rb:14:in `block (3 levels) in <top (required)>'
2) Error:
Cron launcher::initialization#test_0003_does not initialize the poller when interval is 0:
NoMethodError: undefined method `[]' for …
```

Fix tests failing in Sidekiq 6

---

lib/sidekiq/cron/job.rb
lib/sidekiq/cron/views/cron.erb
sidekiq-cron.gemspec

This changes the UI to be more human readable, using the [cronex](https://github.com/alpinweis/cronex) library to generate a human version of each job's cron. It also sets the `title` property of the job's name to the description, so that you're able to hover over the job and see the description without clicking into the show page.

feat: human readable UI

---

lib/sidekiq/cron/job.rb
test/test_helper.rb
test/unit/job_test.rb

ActiveJob queue_as configuration is now used to update Job's queue, previously only Sidekiq::Worker jobs class options were fetched.
As in case with Sidekiq::Workers, queue option in config always takes precedence over queue_as in ActiveJob class.
Fixes #437

 Fetch queue name from ActiveJob class

---

README.md
lib/sidekiq/cron/job.rb

Relates to this [issue](https://github.com/sidekiq-cron/sidekiq-cron/issues/443)
- Logs a warning when we use `symbolize_args: true` without using `active_job: true`.
- Adds this specifity in the README.

Add warning log when 'symbolize_args: true' is used without 'active_job: true'

---

lib/sidekiq/cron/job.rb

Fixes unused variable warning in rescue when running specs.

Fix: unused variable warning

---

README.md

It was not obvious from the docs that this field got persisted when a job gets reloaded if it isn't set explicitly. That means that a job that is disabled in the web UI would still be disabled after a redeployment. This just adds some more documentation to make that abundantly clear.

Readme: clarify that job status gets persisted

---

lib/sidekiq/cron/job.rb
test/unit/job_test.rb

This was not persisting the last enqueued at time when the cron schedule got reloaded during redeployments because it expected all job names to be found at the string key `"name"` instead of the symbol key `:name`. Now symbols keys should work here too.

sidekiq/cron/job: allows symbol keys in .load_from_array!

---

README.md
lib/sidekiq/cron.rb
lib/sidekiq/cron/job.rb
test/unit/job_test.rb

This adds a configuration option for stricter cron string parsing.
Specifically, I wanted to avoid the possibility of a natural language cron string being parsed into multiple cron lines and then everything but the first cron line getting ignored. This is the default when using `Fugit.do_parse_cron`.
```rb
irb(main):005:0> Fugit.do_parse("every day at 3:15 and 4:30")
=> #<Fugit::Cron:0x000000011100e170 @original="15 3 * * *", @cron_s=nil, @day_and=nil, @seconds=[0], @minutes=[15], @hours=[3], @monthdays=nil, @months=nil, @weekdays=nil, @zone=nil, @timezone=nil>
irb(main):006:0> Fugit.do_parse("every day at 3:15 and 4:30", :multi => :fail)
...
ArgumentError (multiple crons in "every day at 3:15 and 4:30" - {:monthday=>(slot :monthday "*" {:weak=>true})})
```
We use the `:multi => :fail` …

Add strict cron parsing mode

---

README.md

It now uses a correct configuration name.

Fix natural language parsing configuration examples in README.md [skip ci]

---

README.md
lib/sidekiq/cron.rb
lib/sidekiq/cron/job.rb
test/unit/job_test.rb

Closes #463.
Naming is hard, so probably people can suggest a better name for this configuration option.
I also refactored a bit the relevant methods to avoid double negation and be simpler to understand.

Add ability to configure the past scheduled time threshold

---

CHANGELOG.md
lib/sidekiq/cron/version.rb

Full diff: https://github.com/sidekiq-cron/sidekiq-cron/compare/v1.12.0...master
@ondrejbartas @honzasterba Do you agree with this release? Since [`namespaces`](https://github.com/sidekiq-cron/sidekiq-cron#namespacing) is a quite big feature (although retro-compatible with v1), I think it's good timing to start a new major. My idea is to launch it first as a release candidate and then, in some weeks, make the official v2 release.

Prepare release v2.0.0.rc1

---

sidekiq-cron.gemspec

https://github.com/floraison/fugit/issues/104
Prevent Fugit::Nat.parse choking on large input, limit at 256 chars

Require at least fugit >= 1.11.1

---

lib/sidekiq/cron/job.rb

Related to https://github.com/sidekiq-cron/sidekiq-cron/issues/471
@markets I fixed it in the most easy way at the moment: by reaching the end of the method we can "suppose" that everything worked as expected and it can return `true`.
Actually, in the `Sidekiq.redis` block we are calling some redis commands (`SADD`, `HSET`, `ZADD`) but the code is not checking their return values. It's unlikely that those commands fail, unless a connection error occurs (but that would raise an expetion, I suppose!). So this might be good enough. What do you think?

Fix: according to documentation, `.create` should return true/false

---

lib/sidekiq/cron/job.rb

Resolves https://github.com/sidekiq-cron/sidekiq-cron/issues/478
The current way of setting values is to use a hash. As noted in the issue attached, this format is marked as deprecated by Ruby 3. The following warning is thrown:
```
/usr/local/bundle/gems/sidekiq-cron-1.10.1/lib/sidekiq/cron/job.rb:472: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```
This will instead pass an array to Redis. This is how [`hmset`](https://www.rubydoc.info/github/ezmobius/redis-rb/Redis:hmset) accepts arguments. Also, `hset` is preferred over `hmset` as Redis has deprecated the `hmset` command.
I was able to get all tests to pass locally
I can also see the keys being set correctly via the `redis-cli`:
```
> HGET cron_job:foo_job description
"A …
```

Update How Redis Values Are Stored on `save`

---

lib/sidekiq/cron/views/cron.erb
lib/sidekiq/cron/views/cron_show.erb
lib/sidekiq/cron/web.rb
sidekiq-cron.gemspec

- Updated the code to use the new API for web extensions in Sidekiq 7.3 and above.
- Added checks to ensure it still works with older Sidekiq versions.
- Removed all inline CSS styles from the views to make the code cleaner.
- Used existing CSS classes instead, so the design stays consistent without extra styles.
- Removed inline styles and used existing CSS classes.
- Simplified some parts of the view to make the code easier to maintain.
- Added logic to register the web extension using the new Sidekiq 7.3+ API.
- Included a fallback for older Sidekiq versions to keep everything working.
- https://github.com/sidekiq/sidekiq/pull/6292
- https://github.com/sidekiq-cron/sidekiq-cron/issues/468#issuecomment-2341467667

Add compatibility with Sidekiq 7.3+ and remove inline styles

---

lib/sidekiq/cron/views/cron.erb

This PR includes two improvements to the `cron.erb` view:
- **Add Confirmation for Disabled Jobs**: Ensures that when attempting to enqueue a disabled cron job, a confirmation dialog (`data-confirm`) is displayed. This brings consistency in behaviour, as the same confirmation is already shown for enabled jobs.
- **Refactor Job Name Escaping**: Replaces repeated occurrences of `CGI.escape(job.name).gsub('+', '%20')` with a single variable `escaped_job_name`, reducing redundancy and improving code readability.
These changes should improve the user experience by preventing accidental enqueuing of disabled jobs and simplify the codebase.
- Closes https://github.com/sidekiq-cron/sidekiq-cron/issues/481

Add confirmation for enqueuing disabled cron jobs and refactor job name escaping

---

lib/sidekiq/cron/job.rb
lib/sidekiq/cron/views/cron.erb
test/unit/job_test.rb

This PR introduces a validation that disallows `*` as a valid namespace in sidekiq-cron jobs. It also fixes an issue where individual job actions like "Enqueue", "Delete", "Enable", and "Disable" fail when all jobs are listed using the '*' wildcard. The job's actual namespace is now correctly referenced for these actions. A test case has been added to ensure `*` is considered an invalid namespace.
Fixes: https://github.com/sidekiq-cron/sidekiq-cron/issues/483

Restrict namespace from using '*' and fix job actions for wildcard namespaces

---

lib/sidekiq/cron/job.rb
test/unit/job_test.rb

This pull request fixes an issue where the `date_as_argument` option in Sidekiq Cron jobs cannot be changed from true to false once it has been set to true. The issue occurs because the Redis key for `date_as_argument` is not removed when the configuration is updated.
- Added logic to delete the `date_as_argument` field from Redis when `date_as_argument` is set to false.
- This ensures that stale values in Redis are cleared, allowing configuration changes to take effect as expected
Fixes: #472

Fix: Ensure date_as_argument option can be set from true to false in Sidekiq Cron jobs

---

lib/sidekiq/cron/web_extension.rb

This PR addresses a redirection issue in the Sidekiq Cron web extension where redirects were not consistently pointing to namespace-specific routes. The changes ensure that after performing operations (`enqueue`, `delete`, `enable`, `disable`) on cron jobs, the user is redirected to the appropriate namespace view.

Fix redirection issues in web extension for namespace-specific routes

---

README.md
lib/sidekiq/cron/job.rb
lib/sidekiq/cron/poller.rb
lib/sidekiq/cron/web_extension.rb
test/unit/job_test.rb
test/unit/web_extension_test.rb

Closes #493 
I was tempted to add an alias for the only "public api" method, as I pointed out in the original issue:
```ruby
alias_method :enqueue!, :enque!
```
But I think we can take advantage that we are going to jump a major version (v2.0) and forget about it.

Rename `enque!` to `enqueue!`. Also, rename all other "_enque_" occurences.

---

README.md
lib/sidekiq-cron.rb
lib/sidekiq/cron.rb
lib/sidekiq/cron/job.rb
lib/sidekiq/cron/launcher.rb
lib/sidekiq/cron/namespace.rb
lib/sidekiq/cron/poller.rb
lib/sidekiq/cron/schedule_loader.rb
test/unit/job_test.rb
test/unit/launcher_test.rb
test/unit/namespace_test.rb
test/unit/poller_test.rb
test/unit/schedule_loader_test.rb
test/unit/web_extension_test.rb

This PR refactors the configuration management in `sidekiq-cron` by moving `cron_poll_interval` and other related options from `Sidekiq::Options` to the `Sidekiq::Cron.configuration`. This change improves separation of concerns by allowing `sidekiq-cron` to manage its own settings independently from sidekiq's core options.

Refactor sidekiq cron configurations

---

lib/sidekiq/cron/views/cron.erb
lib/sidekiq/cron/views/cron_show.erb
test/unit/job_test.rb

Corrected a typo by renaming 'enque' to 'enqueue' in forms and test descriptions.

Fix typo 'enque' to 'enqueue' in forms and tests

---

lib/sidekiq/cron/web_extension.rb

Added the helper method `redirect_to_previous_or_default` to streamline repeated redirect logic.

Refactor: Simplify redirect logic with helper method

---

lib/sidekiq/cron/job.rb
test/test_helper.rb
test/unit/job_test.rb

In https://github.com/sidekiq/sidekiq/commit/7e27a3fbfd3163fd58a17fef8ad6594b92bb3a6c (released in Sidekiq v7.3.3+) Sidekiq introduced the module `Sidekiq::ActiveJob`.
Any reference to `ActiveJob` within `Sidekiq::Cron` therefore does not get resolved to `::ActiveJob`, but to `::Sidekiq::ActiveJob`, thereby breaking `sidekiq-cron`.
We fix this by applying absolute namespacing to references to `ActiveJob`.

Fix detection of ActiveJob

---

README.md
lib/sidekiq/cron/job.rb
test/unit/job_test.rb

This option isn't supported by ActiveJob, which requires retry options to be set at the job class level (via the `retry_on` method) rather at the job instance level.
* Closes #496
* https://github.com/sidekiq/sidekiq/wiki/Error-Handling#configuration

Add `retry` job configuration option to set sidekiq retry job option

---

lib/sidekiq/cron/locales/ja.yml

- Enclose Japanese translation strings with double quotes to prevent YAML parse errors
- Double quotes are necessary when strings contain multi-byte symbols like `？`
- Fixes the "found character that cannot start any token" error
Resolves https://github.com/sidekiq-cron/sidekiq-cron/issues/514

fix: Add quotes to Japanese translations containing multi-byte symbols

---

Gemfile
lib/sidekiq/cron/job.rb
test/test_helper.rb
test/unit/job_test.rb

In `activejob` the class method `MyJob.queue_name` returns a `Proc`. To obtain the actual queue name, we need to invoke the method on an instance of the job class, e.g. `MyJob.new.queue_name`.
The test suite was unable to detect this problem because a mocked version of the `ActiveJob::Base` class was used which did not act in the same way as the actual `activejob` gem.
We fix this by testing against the actual `activejob` gem.
Fixes #512.

Fix usage of ActiveJob::Base.queue_name

---

lib/sidekiq/cron/locales/ja.yml

The translated text contains the words `cron` and `クロン` mixed together. Since it works with `cron`, use `cron`.

Unify with the word `cron` at Japanese

---

README.md

This PR enhances the documentation for Sidekiq::Cron by adding a section on handling namespace renaming. It includes the following updates:
- Explains the potential issue of duplicate cron jobs when renaming a namespace.
- Provides a recommended approach to delete old cron jobs associated with the previous namespace.
- Includes code examples for updating the default namespace and removing old jobs.
These changes aim to prevent issues caused by namespace renaming and provide clear guidance for managing Sidekiq::Cron jobs effectively.
ref:
https://github.com/sidekiq-cron/sidekiq-cron/issues/488#issuecomment-2376599567

Add documentation for renaming Sidekiq::Cron namespaces and managing old jobs

---

.github/workflows/ci.yml
Gemfile
lib/sidekiq/cron/views/cron.erb
lib/sidekiq/cron/web.rb
lib/sidekiq/cron/web_extension.rb
sidekiq-cron.gemspec
test/test_helper.rb
test/unit/web_extension_test.rb

This change will make `sidekiq-cron` functionally compatible with Sidekiq v8.0.0.
Some users may take issue to the placment of the buttons on the web UI
due to `.pull-right` not working anymore. This is left to another developer
with better knowledge of web design.
Fixes #529

Add support for Sidekiq v8

---

lib/sidekiq/cron/views/cron.erb
lib/sidekiq/cron/views/cron_show.erb
lib/sidekiq/cron/views/legacy/cron.erb
lib/sidekiq/cron/views/legacy/cron_show.erb
lib/sidekiq/cron/web_extension.rb

Sidekiq v8 dropped Bootstrap from its assets, so I tried to fix the UI using the same classes used in sidekiq v8 UI, I opted to creating a new v8 folder in views, changes are too many to put conditional rendering in the current views
A more elegant solution would be defining a CSS asset for sidekiq-cron and load it when registering the extension in sidekiq.
- use separate folder for views for >= v8
- use vanilla CSS classes defined by sidekiq UI and drop Bootstrap CSS classes
fixes #537

Properly support Sidekiq v8 new UI

---

lib/sidekiq/cron/job.rb
lib/sidekiq/cron/support.rb

This update simplifies the constantize helper method by utilizing `Object.const_get`. Similar changes have been made in Rails and Sidekiq, as shown in the following PR and commit:
* https://github.com/rails/rails/pull/41877
* https://github.com/sidekiq/sidekiq/commit/68f7b7fffb13162328a8bee60106065911346c99
Since `sidekiq-cron` requires Ruby 2.7 or later, we can adopt this approach as well.

Refactor constantize helper to use `Object.const_get`

---

README.md
lib/sidekiq/cron/schedule_loader.rb

After accidently adding a typo in a class name on the schedule, and [thankfully] having it caught in a PR, I wanted a better way to test the schedule in my project.
This Pull Request has been created because it enables the same schedule loader that runs in production to be called in a testing environment. This way, we have the ability to show that there are no configuration errors.
This Pull Request changes the implementation of ScheduleLoader to enable consumers of the library to test their schedule in an environment where redis is running but the Sidekiq service is not (this is usual for testing environments).
As this change is purely an implementation detail, I have not added or changed any tests.
I have added an example of how to test projects in the readme.

Allow testing of schedule by library consumers

---

lib/sidekiq/cron/schedule_loader.rb
test/unit/schedule_loader_test.rb

Fixes #507
I believe this is the correct implementation. It moves all schedule loading to happen on sidekiq startup which is after the initializers have ran. This means that any change to `config.cron_schedule_file` in an initializer will be respected.
**However, please consider the very real possibility that someone has created a `config/schedule.yml` file but has then blindly copied the configuration from [here](https://github.com/sidekiq-cron/sidekiq-cron/?tab=readme-ov-file#configuration). They may not not have a `config/my_schedule.yml` file but this does not currently matter as that setting is effectively ignored.**
In the above example, that person may upgrade their sidekiq-cron gem only to find that their schedule stops being loaded. As such, I think there is a decision to be …

Load schedule file within sidekiq callback

---

lib/sidekiq/cron/namespace.rb
test/unit/namespace_test.rb

Looks like a bug: currently, if `available_namespaces` is provided (e.g. `%w[namespace-1 namespace-2]`) then there's no `default_namespace` in the list.

Fix missing default namespace if namespaces are explicitly provided

---

README.md

I'd suggest adding `rubocop-md` to ensure README snippets are valid

Fix invalid README.md ruby code snippet

---

CHANGELOG.md
README.md
lib/sidekiq/cron.rb
lib/sidekiq/cron/job.rb
lib/sidekiq/cron/namespace.rb
test/unit/job_test.rb
test/unit/namespace_test.rb
test/unit/web_extension_test.rb

The default for `available_namespaces` is now `[config.default_namespaces]`.
See https://github.com/sidekiq-cron/sidekiq-cron/issues/516

Rework namespaces feature

---

lib/sidekiq/cron/job.rb

```shell
lib/sidekiq/cron/job.rb:382: warning: assigned but unused variable - e
lib/sidekiq/cron/job.rb:595: warning: method redefined; discarding old args=
lib/sidekiq/cron/job.rb:599: warning: method redefined; discarding old cron_expression_string
```

Fix some Ruby warnings

---

lib/sidekiq/cron/views/cron.erb
lib/sidekiq/cron/views/cron_show.erb
test/unit/web_extension_test.rb

The "Enqueue Now" button was not working because HTML does not allow forms to be nested. Nesting forms can cause unexpected behavior and conflicts in form submission.
Fixes #562

Fix manually launch enqueue job not working from web ui
