sidekiq-cron/sidekiq-cron

- lib/sidekiq/cron/views/cron.erb
- lib/sidekiq/cron/views/cron.slim
> Escape Cron Job name so it can be enqueued/disabled/enabled/delete by fronted

- README.md
Thanks for your awesome work! Here are some improvements to the README file from a grammatical point of view. I also tried to normalize the name Sidekiq to use capitalization everywhere, and added a few Markdown backticks.
> README grammatical and typo corrections

- test/test_helper.rb
https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/web.rb#L15
Tests should use `ENV['RACK_ENV']='test'` to make pass all the tests for the latest sidekiq versions.
> Lets use RACK_ENV='test' for skipping authentication process in sidekiq web app

- lib/sidekiq/cron/locales/de.yml
- lib/sidekiq/cron/locales/en.yml
- lib/sidekiq/cron/locales/ru.yml
- lib/sidekiq/cron/views/cron.erb
Hello! Thank you for awesome gem!
I've added russian locale.
Also I've added separate string for cron string title in table header as menu tab and table header need to be different.
Here is what it looks like:
> Add Russian locale

- lib/sidekiq/cron/job.rb
- lib/sidekiq/cron/poller.rb
- test/unit/job_test.rb
- test/unit/poller_test.rb
See https://github.com/ondrejbartas/sidekiq-cron/issues/142
This changes fix my mentioned problems, but 2 tests are broken... Maybe someone can take a look at it? 
My knowledge in this gem is not deep enough at the moment.
> UTC timezone fix

- lib/sidekiq/cron/locales/en.yml
- lib/sidekiq/cron/views/cron.erb
- lib/sidekiq/cron/views/cron.slim
- lib/sidekiq/cron/web_extension.rb
- test/unit/web_extension_test.rb
> Add actions for all jobs to view

- lib/sidekiq/cron/locales/ja.yml
Hi. I added a Japanese locale file for the project.
Thanks.
> Add Japanese locale

- lib/sidekiq/cron/locales/ja.yml
Specify the message of Japanese locale
Follow up of #165
> Specify the message of Japanese locale

- .travis.yml
- lib/sidekiq/cron/launcher.rb
- lib/sidekiq/cron/poller.rb
- test/integration/performance_test.rb
* Better to use `Module.prepend` for monkey patching
* Use `Sidekiq.logger`, like in original sidekiq (this can fix issue https://github.com/ondrejbartas/sidekiq-cron/issues/259)
> Improve patching and logging

- lib/sidekiq/cron/job.rb
- test/unit/job_test.rb
ref https://github.com/ondrejbartas/sidekiq-cron/pull/245
This check more properly the argument to avoid sidekiq load error
cheers
> Check its an hash on load from hash to avoid errors

- lib/sidekiq/cron/job.rb
- test/unit/job_test.rb
Reverts ondrejbartas/sidekiq-cron#246
You need to know there is an error. Without this check you will fail silently and nobody will knoow about not added jobs :/
> Revert "Check its an hash on load from hash to avoid errors"

- lib/sidekiq/cron/views/cron.erb
fix #308
Fix "Show All" button on cron jobs view with Sidekiq 6.3.0+.
I confirm the error has been fixed on Sidekiq v6.3.0, and v6.4.1.
I also confirm it works on Sidekiq v6.2.2 as always.
> [UI] Fix "Show All" button on cron jobs view with Sidekiq 6.3.0+

- lib/sidekiq/cron/views/cron.erb
- lib/sidekiq/cron/views/cron_show.erb
Changes the button classes to the ones used in sidekiq.
fixes #260
> Support Dark Mode

- Changes.md
- lib/sidekiq/cron/version.rb
**EXTRAS**
- fixed some typos and styling issues in Changelog
**SELF-NOTES**
- Run `rake release` after merging this to `master`
> Prepare release v1.4.0

- lib/sidekiq/cron/locales/pt.yml
Adds Portuguese language translation. (pt/pt-BR)
> feat: add portuguese translation file

- lib/sidekiq/cron/poller.rb
> Fixes an issue that prevented the gem to work in previous versions

- CHANGELOG.md
- lib/sidekiq/cron/version.rb
**DIFF** https://github.com/ondrejbartas/sidekiq-cron/compare/v1.7.0...master
(I'll squash at the end)
> Prepare release v1.8.0

- test/integration/performance_test.rb
This test randomly crashes in our CI (usually on Ruby 3.0), so change 50s -> 60s.
Took the opportunity to de-hardcode some variables in descriptions and asserts.
> [ci] stabilize performance test

- README.md
- lib/sidekiq/cron/job.rb
- lib/sidekiq/cron/launcher.rb
- lib/sidekiq/cron/poller.rb
- lib/sidekiq/options.rb
- test/integration/performance_test.rb
- test/test_helper.rb
- test/unit/job_test.rb
- test/unit/launcher_test.rb
- test/unit/poller_test.rb
- test/unit/schedule_loader_test.rb
- test/unit/web_extension_test.rb
Sidekiq v7 support 🎉 
Closes #378
Closes #370
Closes #357
> Support Sidekiq 7

- CHANGELOG.md
- README.md
- lib/sidekiq/cron/version.rb
- test/test_helper.rb
**Changes:** https://github.com/sidekiq-cron/sidekiq-cron/compare/v1.8.0...prepare_v1.9.0
> Prepare release v1.9.0 🚀 

- Gemfile
- lib/sidekiq/cron/job.rb
- sidekiq-cron.gemspec
See: https://github.com/floraison/fugit/issues/70.
In terms of code, this is almost the same as before #312, but using new Fugit APIs.
Thanks to @jmettraux 🤝
> Clean up cron parser code, by using new Fugit API

- CHANGELOG.md
- lib/sidekiq/cron/version.rb
**Diff:** https://github.com/sidekiq-cron/sidekiq-cron/compare/v1.9.0...prepare_v1.9.1
> Prepare new release v1.9.1

- CHANGELOG.md
- lib/sidekiq/cron/version.rb
Full diff: https://github.com/sidekiq-cron/sidekiq-cron/compare/v1.9.1...master
> Prepare next release (v1.10.0) 🚀

- CHANGELOG.md
- lib/sidekiq/cron/version.rb
Diff: https://github.com/sidekiq-cron/sidekiq-cron/compare/v1.10.0...master
> Prepare next release (v1.10.1) 🚀

- sidekiq-cron.gemspec
Fixes CI
https://github.com/freerange/mocha/issues/614
> Update to mocha 2.1 to pick up minitest fix

- lib/sidekiq/cron/schedule_loader.rb
- test/unit/job_test.rb
- test/unit/schedule_loader_test.rb
fixes #426
This reverts commit 48c2563a77fb9dac4ef4e881bf934ae67f1f42ab.
> Undo clear jobs while loading the schedule

- README.md
- lib/sidekiq/cron/job.rb
- lib/sidekiq/cron/schedule_loader.rb
- test/unit/job_test.rb
- test/unit/schedule_loader_test.rb
> Differentiates b/w schedule vs dynamic jobs + Clears scheduled jobs upon schedule load

- CHANGELOG.md
> Fix v1.4.0 dark mode support PR link

- CHANGELOG.md
- lib/sidekiq/cron/version.rb
Diff: https://github.com/sidekiq-cron/sidekiq-cron/compare/v1.10.1...master
> Prepare next release (v1.11.0) 🚀

- lib/sidekiq/cron/job.rb
In Sidekiq 7, calls to `Sidekiq.redis` checks out a connection from an internal connection pool instead of the connection pool used by the job processors. If a connection is checked out but not used, it's possible that the heartbeat thread won't keep the connection alive before the Redis server client timeout.
To avoid this, update the checks to return earlier if the Redis connection is not needed.
This might help reduce intermittent `Broken pipe` errors as reported in https://github.com/redis-rb/redis-client/issues/119.
> Only check out a Redis connection if necessary

- CHANGELOG.md
- lib/sidekiq/cron/version.rb
Diff: https://github.com/sidekiq-cron/sidekiq-cron/compare/v1.11.0...master
> Prepare next release (v1.12.0) 🚀

- lib/sidekiq/cron/job.rb
This always bothered me a little 😅 I think it's more natural to have `attr_accessor`s and the `initialize` method at the beginning of the class.
> Move class attributes and initialize method at the beginning of the file

- README.md
> [docs] Clarify worker => process + other small enhancements

- README.md
- lib/sidekiq/cron/web.rb
> Require Namespace when booting web UI (see #486) + Documentation tweaks

- lib/sidekiq/cron/job.rb
Since we are requiring now Sidekiq 6.5+ (it requires Redis >= 4.5.0), we can already remove support for old Redis.
> Remove useless support for old Redis (< 4.2)

- CHANGELOG.md
- lib/sidekiq/cron/version.rb
Hopefully this is the latest round before final v2 release 🎉 
Please, don't forget to try it in your testing/staging environment and report any 🙏🏼 issue.
> Prepare v2.0.0.rc2 release

- CHANGELOG.md
- lib/sidekiq/cron/version.rb
- Changes since latest release candidate: https://github.com/sidekiq-cron/sidekiq-cron/compare/v2.0.0.rc2...master
- Changes from latest v1: https://github.com/sidekiq-cron/sidekiq-cron/compare/v1.12.0...master
Thank you everyone involved in this release! 👏🏼
> Prepare release: v2.0.0 🎉 

- CHANGELOG.md
- Gemfile
- lib/sidekiq/cron/version.rb
- test/integration/performance_test.rb
Diff: https://github.com/sidekiq-cron/sidekiq-cron/compare/v2.0.0...master
> Prepare release v2.0.1

- README.md
- lib/sidekiq/cron.rb
- lib/sidekiq/cron/job.rb
- lib/sidekiq/cron/namespace.rb
- test/test_helper.rb
- test/unit/job_test.rb
- test/unit/namespace_test.rb
- test/unit/web_extension_test.rb
Resolves https://github.com/sidekiq-cron/sidekiq-cron/issues/516
> Add `available_namespaces` configuration option

- CHANGELOG.md
- README.md
- lib/sidekiq/cron/version.rb
Full diff: https://github.com/sidekiq-cron/sidekiq-cron/compare/v2.0.1...master
> Prepare release v2.1.0

- CHANGELOG.md
- lib/sidekiq/cron/version.rb
Full diff: https://github.com/sidekiq-cron/sidekiq-cron/compare/v2.1.0...master
> Prepare new release v2.2.0 🚀

- lib/sidekiq/cron/schedule_loader.rb
- test/unit/schedule_loader_test.rb
> Allow for sidekiq embedded configuration

- test/integration/performance_test.rb
- test/support/classes.rb
- test/unit/job_test.rb
- test/unit/web_extension_test.rb
`bundle exec rubocop --plugin rubocop-minitest --plugin rubocop-performance --only Lint,Performance,Minitest test`
> Fix test-related RuboCop offenses

- README.md
- For testing the schedule loading process
In response to https://github.com/sidekiq-cron/sidekiq-cron/pull/543#issuecomment-2822333366
> Update readme to show the correct method name.

- CHANGELOG.md
- lib/sidekiq/cron/version.rb
Full diff: https://github.com/sidekiq-cron/sidekiq-cron/compare/v2.2.0...master
> Prepare new release v2.3.0 🚀
